LOCAL_PATH:= $(call my-dir)
include \$(CLEAR_VARS)
LOCAL_MODULE := TimeService
LOCAL_MODULE_PATH := $(TARGET_OUT)/app/
LOCAL_SRC_FILES := TimeService.apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS 
LOCAL_MODULE_SUFFIX:=$(COMMON_ANDROID_PACKAGE_SUFFIX) 
LOCAL_CERTIFICATE := platform
include \$(BUILD_PREBUILT)